
from datetime import datetime

# Get the current local date
current_date = datetime.now()

# Format the date as a string in the desired format
formatted_date = current_date.strftime('%-m/%-d/%Y')

numbers = {
  "case": "caseImage",
  "repeat": "repeatImage",
  "return": "returnImage",
  "0": "zero",
  "1": "one",
  "2": "two",
  "3": "three",
  "4": "four",
  "5": "five",
  "6": "six",
  "7": "seven",
  "8": "eight",
  "9": "nine"
}

file = open("Sources/SFSymbolsKit/NSImage+Extension.swift", "w")

file.write("//\n")
file.write("//  NSImage+Extension.swift\n")
file.write("//  SFSymbols\n")
file.write("//\n")
file.write(f"//  Generated by SFSymbolsKit on {formatted_date}\n")
file.write("//\n")
file.write("\n")
file.write("#if canImport(AppKit)\n")
file.write("import AppKit\n")
file.write("\n")
file.write("@available(macOS 11.0, *)\n")
file.write("public extension NSImage {\n")
file.write("    /// This enum provides static properties, each corresponding to an SFSymbol and returning an `NSImage`. The corresponding SFSybmol to each property can be found in the SFSybmols App.\n")
file.write("    enum SFSymbols {\n")

with open('SFSymbols.txt') as topo_file:
    for line in topo_file:
        parts = line.split('.')
        camelCaseName = ""
        
        for part in parts:
            if part == parts[0]:
            
                if part.rstrip() in numbers:
                    camelCaseName += numbers[part.rstrip()]
                    continue
                elif part[0] in numbers:
                    camelCaseName += numbers[part[0]] + part[1:]
                    continue
                camelCaseName += part
                continue
            camelCaseName += part.capitalize()
            
        result = "        static let {} = getSystemImage(named: SFSymbol.{}.rawValue)\n".format(camelCaseName.rstrip(), camelCaseName.rstrip())
        file.write(result)
        
file.write("\n")
file.write("        /// This `private` method is a helper that provides an `NSImage`.\n")
file.write("        /// - Parameter named: The name of the SFSymbol.\n")
file.write("        /// - Returns: The named SFSymbol as an `NSImage`.\n")
file.write("        private static func getSystemImage(named: String) -> NSImage {\n")
file.write("            guard let image = NSImage(systemSymbolName: named, accessibilityDescription:  \"This is the symbole for\\(named)\")\n")
file.write("            else { return NSImage() }\n")
file.write("            return image\n")
file.write("        }\n")
file.write("    }\n")
file.write("}\n")
file.write("#endif\n")
file.close()

