
from datetime import datetime

# Get the current local date
current_date = datetime.now()

# Format the date as a string in the desired format
formatted_date = current_date.strftime('%-m/%-d/%Y')

numbers = {
  "case": "caseImage",
  "repeat": "repeatImage",
  "return": "returnImage",
  "0": "zero",
  "1": "one",
  "2": "two",
  "3": "three",
  "4": "four",
  "5": "five",
  "6": "six",
  "7": "seven",
  "8": "eight",
  "9": "nine"
}

file = open("Sources/SFSymbolsKit/String+Extension.swift", "w")

file.write("//\n")
file.write("//  String+Extension.swift\n")
file.write("//  SFSymbols\n")
file.write("//\n")
file.write(f"//  Generated by SFSymbolsKit on {formatted_date}\n")
file.write("//\n")
file.write("\n")
file.write("public extension String {\n")
file.write("    /// This enum provides static properties, each corresponding to an SFSymbol and returning a `String`. The corresponding SFSybmol to each property can be found in the SFSybmols App.\n")
file.write("    public enum SFSymbols {\n")

with open('SFSymbols.txt') as topo_file:
    for line in topo_file:
        parts = line.split('.')
        camel_case_name = ""
        for part in parts:
            if part == parts[0]:
            
                if part.rstrip() in numbers:
                    camel_case_name += numbers[part.rstrip()]
                    continue
                elif part[0] in numbers:
                    camel_case_name += numbers[part[0]] + part[1:]
                    continue
                camel_case_name += part
                continue
            camel_case_name += part.capitalize()
            
        result = "        static let {}: String = SFSymbol.{}.rawValue\n".format(camel_case_name.rstrip(), camel_case_name.rstrip())
        file.write(result)
file.write("    }\n")
file.write("}\n")
file.close()
