from datetime import date

numbers = {
  "case": "caseImage",
  "repeat": "repeatImage",
  "return": "returnImage",
  "0": "zero",
  "1": "one",
  "2": "two",
  "3": "three",
  "4": "four",
  "5": "five",
  "6": "six",
  "7": "seven",
  "8": "eight",
  "9": "nine"
}

file = open("../Sources/SFSymbols/Enum.swift", "w")

file.write("//\n")
file.write("//  SFSymbol.swift\n")
file.write("//  SFSymbols\n")
file.write("//\n")
file.write("//  Generated by Enum.py on ")
file.write(date.today().strftime('%m/%d/%y'))
file.write(".\n")
file.write("//\n")
file.write("\n")
file.write("/// `SFSymbol` is an enum with a case for every SFSymbol. Cases are each the string name for the symbol. Cases are generated.\n")
file.write("public enum SFSymbol: String, CaseIterable {\n")
file.write("\n")

with open('SFSymbols.txt') as topo_file:
    for line in topo_file:
        parts = line.split('.')
        camelCaseName = ""
        
        for part in parts:
            if part == parts[0]:
            
                if part.rstrip() in numbers:
                    camelCaseName += numbers[part.rstrip()]
                    continue
                elif part[0] in numbers:
                    camelCaseName += numbers[part[0]] + part[1:]
                    continue
                camelCaseName += part
                continue
            camelCaseName += part.capitalize()
            
        result = "    case {} = \"{}\"\n".format(camelCaseName.rstrip(), line.rstrip())
        file.write(result)
file.write("\n")
file.write("    /// `string` is a computed propterty that maps the case to it's corresponding ``String``.\n")
file.write("    public var string: String {\n")
file.write("        return self.rawValue\n")
file.write("    }\n")
file.write("\n")
file.write("}\n")
file.close()
