//
//  EnumUIKit+Extension.swift
//  SFSymbols
//
//  Generated by EnumUIKitExtension.py on 07/11/23.
//

#if canImport(UIKit)
import UIKit

/// This extension contains `UIKIt` computed properties to make using [SFSymbols](https://developer.apple.com/sf-symbols/) easier.
public extension SFSymbol {
    /// `image` is a computed propterty that maps the case to it's corresponding ``UIImage``.
    var image: UIImage {
        guard let image = UIImage(systemName: self.rawValue)
        else { return UIImage() }
        return image
    }
}
#endif
