//
//  EnumAppKit+Extension.swift
//  SFSymbols
//
//  Generated by EnumAppKitExtension.py on 07/11/23.
//

#if canImport(AppKit)
import AppKit

/// This extension contains `UIKIt` computed properties to make using [SFSymbols](https://developer.apple.com/sf-symbols/) easier.
public extension SFSymbol {
    /// `image` is a computed propterty that maps the case to it's corresponding ``UIImage``.
    var image: NSImage {
        guard let image = NSImage(named: self.rawValue)
        else { return NSImage() }
        return image
    }
}
#endif
