title: SFSymbolsKit
description: Apple's entire SF Symbols catalog as a strongly-typed Swift API.
url: https://sfsymbolskit.com
github_username: WikipediaBrown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache
  - .jekyll-cache
  - iOS-Coverage
  - macOS-Coverage
  - iOS-Coverage 2
  - "*.xccovarchive"
  - "*.xccovreport"
